language: python
python: 3.7
install:
  - cp contrib/env-sample .env
  - pip install -r requirements.txt
script:
  - python manage.py test
  - coverage run --source=eventex manage.py test
after_success:
  coveralls